export default function RootHead() {
  return (
    <>
      <title>Practice Next.js with this App</title>

      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
